### ISSUE TITLE
issue with unzipping pngs

### ISSUE THREAD

**Issue by ovord** [FortuneN/cordova-plugin-zeep#3]
Hello,

we are trying to use your plugin for unzipping maptiles of png datatype. The result we get is a partly correct png with pixel errors in it. have a look at the attachment.

![726](https://cloud.githubusercontent.com/assets/12304483/25859201/1aaa936a-34de-11e7-829e-983f16d70c52.png)

would be nice if you could help, otherwise the plugin  works nicly!

**Comment by FortuneN** [comment]
Send me an example file and
Let me know which platform (iOS, android or windows)

**Comment by ovord** [comment]
Hello,

the error was on Windows. We follow a different Approach with zipping now, so i can´t provide you another example file.

Thanks
Oliver
